# Generated by Django 6.0.3 on 2026-03-22 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('nationality', models.CharField(max_length=100)),
                ('zambian_phone', models.CharField(max_length=20)),
                ('personal_email', models.EmailField(max_length=254)),
                ('profile_photo', models.FileField(blank=True, null=True, upload_to='registration_photos/')),
                ('status', models.CharField(choices=[('pending_admin', 'Pending Admin Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_admin', max_length=20)),
                ('review_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('notification_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('qualifications', models.TextField()),
                ('department', models.CharField(max_length=150)),
                ('position_applying_for', models.CharField(max_length=150)),
                ('approved_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved_account', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('nationality', models.CharField(max_length=100)),
                ('zambian_phone', models.CharField(max_length=20)),
                ('personal_email', models.EmailField(max_length=254)),
                ('profile_photo', models.FileField(blank=True, null=True, upload_to='registration_photos/')),
                ('status', models.CharField(choices=[('pending_admin', 'Pending Admin Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_admin', max_length=20)),
                ('review_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('notification_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('date_of_birth', models.DateField()),
                ('guardian_name', models.CharField(max_length=150)),
                ('guardian_relationship', models.CharField(max_length=100)),
                ('guardian_phone', models.CharField(max_length=20)),
                ('guardian_email', models.EmailField(max_length=254)),
                ('previous_school_attended', models.CharField(max_length=200)),
                ('last_grade_completed', models.CharField(max_length=50)),
                ('year_of_completion', models.PositiveIntegerField()),
                ('target_grade', models.CharField(choices=[('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12')], max_length=20)),
                ('last_report_card', models.FileField(blank=True, null=True, upload_to='student_documents/report_cards/')),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='student_documents/birth_certificates/')),
                ('transfer_letter', models.FileField(blank=True, null=True, upload_to='student_documents/transfer_letters/')),
                ('approved_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved_account', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=10)),
                ('recipient', models.CharField(max_length=150)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('response_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='accounts.staffregistration')),
                ('student_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='accounts.studentregistration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
