# Generated by Codex on 2026-03-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_staffregistration_studentregistration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentregistration",
            name="address",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentregistration",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Not Specified", "Not Specified")],
                default="Not Specified",
                max_length=20,
            ),
        ),
        migrations.RenameField(
            model_name="studentregistration",
            old_name="last_grade_completed",
            new_name="last_grade_attended",
        ),
        migrations.RemoveField(
            model_name="studentregistration",
            name="year_of_completion",
        ),
    ]
