# Generated by Codex on 2026-03-30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRegister",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                (
                    "save_mode",
                    models.CharField(
                        choices=[("auto", "Auto Save"), ("manual", "Manual Save")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("total_students", models.PositiveIntegerField(default=0)),
                ("present_count", models.PositiveIntegerField(default=0)),
                ("absent_count", models.PositiveIntegerField(default=0)),
                ("late_count", models.PositiveIntegerField(default=0)),
                ("excused_count", models.PositiveIntegerField(default=0)),
                ("pdf_snapshot", models.FileField(blank=True, null=True, upload_to="attendance_registers/")),
                ("pdf_generated_at", models.DateTimeField(blank=True, null=True)),
                ("last_saved_at", models.DateTimeField(auto_now=True)),
                (
                    "saved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_registers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_registers",
                        to="academics.schoolclass",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "school_class__name", "school_class__section"],
            },
        ),
        migrations.CreateModel(
            name="ClassNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("attachment", models.FileField(upload_to="class_notes/")),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="academics.schoolclass",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notes",
                        to="academics.subject",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_notes",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "school_class__name", "title"],
            },
        ),
        migrations.AddConstraint(
            model_name="attendanceregister",
            constraint=models.UniqueConstraint(fields=("date", "school_class"), name="unique_daily_attendance_register"),
        ),
    ]
