# Generated by Django 6.0.3 on 2026-03-30 21:23

import django.db.models.deletion
from django.db import migrations, models


def seed_zambian_academic_defaults(apps, schema_editor):
    ExaminationType = apps.get_model('academics', 'ExaminationType')
    GradingSystem = apps.get_model('academics', 'GradingSystem')
    Grade = apps.get_model('academics', 'Grade')

    end_of_term, _ = ExaminationType.objects.get_or_create(
        name='End of Term',
        defaults={'weight_percentage': 100, 'applicable_from_grade': 1, 'applicable_to_grade': 12},
    )
    ExaminationType.objects.get_or_create(
        name='Mid-Term',
        defaults={'weight_percentage': 100, 'applicable_from_grade': 1, 'applicable_to_grade': 12},
    )
    ExaminationType.objects.get_or_create(
        name='Mock Exam',
        defaults={'weight_percentage': 100, 'applicable_from_grade': 9, 'applicable_to_grade': 12},
    )

    default_rules = [
        ('A', 80, 100, 'Excellent'),
        ('B', 60, 79, 'Very Good'),
        ('C', 50, 59, 'Good'),
        ('D', 40, 49, 'Pass'),
        ('F', 0, 39, 'Needs Improvement'),
    ]
    for grade_name, min_score, max_score, remark in default_rules:
        GradingSystem.objects.get_or_create(
            grade_name=grade_name,
            defaults={
                'min_score': min_score,
                'max_score': max_score,
                'remark': remark,
                'is_active': True,
            },
        )

    Grade.objects.filter(examination_type__isnull=True).update(examination_type=end_of_term)


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_attendanceregister_classnote'),
        ('students', '0003_student_nationality_alter_student_gender'),
        ('teachers', '0002_teacher_department_teacher_nationality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='ExaminationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('weight_percentage', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('applicable_from_grade', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'), (5, 'Grade 5'), (6, 'Grade 6'), (7, 'Grade 7'), (8, 'Grade 8'), (9, 'Grade 9'), (10, 'Grade 10'), (11, 'Grade 11'), (12, 'Grade 12')], null=True)),
                ('applicable_to_grade', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'), (5, 'Grade 5'), (6, 'Grade 6'), (7, 'Grade 7'), (8, 'Grade 8'), (9, 'Grade 9'), (10, 'Grade 10'), (11, 'Grade 11'), (12, 'Grade 12')], null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GradingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=2)),
                ('min_score', models.PositiveSmallIntegerField()),
                ('max_score', models.PositiveSmallIntegerField()),
                ('remark', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-max_score', 'grade_name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectGradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.PositiveSmallIntegerField(choices=[(1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'), (5, 'Grade 5'), (6, 'Grade 6'), (7, 'Grade 7'), (8, 'Grade 8'), (9, 'Grade 9'), (10, 'Grade 10'), (11, 'Grade 11'), (12, 'Grade 12')])),
                ('is_core', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['grade_level', 'subject__name'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_number', models.PositiveSmallIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ['-academic_year__year', 'term_number'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='grade',
            name='unique_student_subject_term_grade',
        ),
        migrations.AddField(
            model_name='grade',
            name='examination_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='academics.examinationtype'),
        ),
        migrations.AddConstraint(
            model_name='gradingsystem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('grade_name',), name='unique_active_grade_name'),
        ),
        migrations.AddField(
            model_name='subjectgradelevel',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_levels', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='term',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='grade',
            name='term_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='academics.term'),
        ),
        migrations.RunPython(seed_zambian_academic_defaults, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('student', 'subject', 'term', 'examination_type'), name='unique_student_subject_term_exam_type_grade'),
        ),
        migrations.AddConstraint(
            model_name='subjectgradelevel',
            constraint=models.UniqueConstraint(fields=('subject', 'grade_level'), name='unique_subject_grade_level'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('academic_year', 'term_number'), name='unique_academic_year_term_number'),
        ),
    ]
